### ISSUE TITLE
State not working if you don't add it to AutoStart

### ISSUE THREAD

**Issue by BanCrash** [Simon-12/vanguard-out#1]
Hi,

If I disable Vanguard and save state, but don't add it to AutoStart, after closing and opening again Vanguard Out (without restarting computer) it will say that Vanguard is enabled, when it's not.

**Comment by Simon-12** [comment]
Hi, 

thanks for your message. 
Indeed after the application start, it checks if the shortcut is added to the startup folder. When I think about it, this does not make much sense and I am not sure why I added it this way.

I will fix this and release an update.

Cheers

**Comment by BanCrash** [comment]
> Hi,
> 
> thanks for your message. Indeed after the application start, it checks if the shortcut is added to the startup folder. When I think about it, this does not make much sense and I am not sure why I added it this way.
> 
> I will fix this and release an update.
> 
> Cheers

Perfect, thanks!

**Comment by BanCrash** [comment]
> Fixed and released a new version.

Perfect, thanks!
